/**
 * Report Export Service
 * Handles exporting AnalysisReport to PDF and Markdown formats
 */

import type { AnalysisReport, Finding, ProjectReport } from "../types.js";
import puppeteer from "puppeteer";

export class ReportExportService {
  /**
   * Export AnalysisReport to Markdown format
   */
  static async exportToMarkdown(report: AnalysisReport): Promise<string> {
    const lines: string[] = [];

    // Header
    lines.push(`# Analysis Report: ${report.type.replace(/_/g, " ").toUpperCase()}`);
    lines.push("");
    lines.push(`**Report ID:** ${report.id}`);
    lines.push(`**Started:** ${new Date(report.startedAt).toISOString()}`);
    if (report.completedAt) {
      lines.push(`**Completed:** ${new Date(report.completedAt).toISOString()}`);
    }
    lines.push(`**Projects:** ${report.projectIds.length}`);
    lines.push("");

    // Summary
    lines.push("## Summary");
    lines.push("");
    lines.push(report.summary);
    lines.push("");

    // Project Reports
    if (report.projectReports && report.projectReports.length > 0) {
      lines.push("## Project Reports");
      lines.push("");

      for (const pr of report.projectReports) {
        lines.push(`### ${pr.projectName}`);
        lines.push("");
        lines.push(`- **Health Score:** ${pr.healthScore}/100`);
        lines.push(`- **Open Issues:** ${pr.openIssues}`);
        lines.push(`- **Open PRs:** ${pr.openPRs}`);
        lines.push(`- **CI Status:** ${pr.ciStatus}`);

        if (pr.risks.length > 0) {
          lines.push("");
          lines.push("**Risks:**");
          for (const risk of pr.risks) {
            lines.push(`- ${risk}`);
          }
        }
        lines.push("");
      }
    }

    // Findings
    if (report.findings.length > 0) {
      lines.push("## Findings");
      lines.push("");

      const findingsBySeverity = this.groupFindingsBySeverity(report.findings);

      for (const severity of ["critical", "error", "warning", "info"] as const) {
        const findings = findingsBySeverity[severity];
        if (findings && findings.length > 0) {
          lines.push(`### ${severity.toUpperCase()} (${findings.length})`);
          lines.push("");

          for (const finding of findings) {
            lines.push(`#### ${finding.title}`);
            lines.push("");
            lines.push(`**Category:** ${finding.category}`);
            lines.push(`**Project:** ${finding.projectId}`);
            lines.push("");
            lines.push(finding.description);
            lines.push("");
          }
        }
      }
    }

    // Generated Tasks
    if (report.generatedTasks.length > 0) {
      lines.push("## Generated Tasks");
      lines.push("");
      lines.push(`This analysis generated **${report.generatedTasks.length}** tasks.`);
      lines.push("");
      lines.push("Task IDs:");
      for (const taskId of report.generatedTasks) {
        lines.push(`- ${taskId}`);
      }
      lines.push("");
    }

    // Footer
    lines.push("---");
    lines.push(`*Generated by Envisionbot on ${new Date().toISOString()}*`);

    return lines.join("\n");
  }

  /**
   * Export AnalysisReport to PDF format
   */
  static async exportToPDF(report: AnalysisReport): Promise<Buffer> {
    const html = this.generateHTML(report);

    const browser = await puppeteer.launch({
      headless: true,
      args: ["--no-sandbox", "--disable-setuid-sandbox"],
    });

    try {
      const page = await browser.newPage();
      await page.setContent(html, { waitUntil: "networkidle0" });

      const pdfBuffer = await page.pdf({
        format: "A4",
        margin: {
          top: "20mm",
          right: "20mm",
          bottom: "20mm",
          left: "20mm",
        },
        printBackground: true,
      });

      return pdfBuffer;
    } finally {
      await browser.close();
    }
  }

  /**
   * Generate HTML content for PDF export
   */
  private static generateHTML(report: AnalysisReport): string {
    const findingsBySeverity = this.groupFindingsBySeverity(report.findings);

    return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Analysis Report - ${report.id}</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      line-height: 1.6;
      color: #333;
      background: #fff;
    }

    .container {
      max-width: 900px;
      margin: 0 auto;
      padding: 20px;
    }

    h1 {
      color: #1a1a1a;
      margin-bottom: 20px;
      font-size: 32px;
      border-bottom: 3px solid #007bff;
      padding-bottom: 10px;
    }

    h2 {
      color: #2c3e50;
      margin-top: 30px;
      margin-bottom: 15px;
      font-size: 24px;
      border-bottom: 2px solid #e0e0e0;
      padding-bottom: 8px;
    }

    h3 {
      color: #34495e;
      margin-top: 20px;
      margin-bottom: 10px;
      font-size: 20px;
    }

    h4 {
      color: #555;
      margin-top: 15px;
      margin-bottom: 8px;
      font-size: 16px;
    }

    .metadata {
      background: #f8f9fa;
      padding: 15px;
      border-radius: 5px;
      margin-bottom: 20px;
      border-left: 4px solid #007bff;
    }

    .metadata p {
      margin: 5px 0;
    }

    .metadata strong {
      color: #495057;
    }

    .summary {
      background: #e8f4f8;
      padding: 15px;
      border-radius: 5px;
      margin: 15px 0;
      border-left: 4px solid #17a2b8;
    }

    .project-report {
      background: #fff;
      border: 1px solid #dee2e6;
      border-radius: 5px;
      padding: 15px;
      margin-bottom: 15px;
    }

    .project-report ul {
      list-style: none;
      padding-left: 0;
    }

    .project-report li {
      padding: 5px 0;
    }

    .finding {
      background: #fff;
      border: 1px solid #dee2e6;
      border-radius: 5px;
      padding: 15px;
      margin-bottom: 15px;
      page-break-inside: avoid;
    }

    .severity-critical {
      border-left: 4px solid #dc3545;
    }

    .severity-error {
      border-left: 4px solid #fd7e14;
    }

    .severity-warning {
      border-left: 4px solid #ffc107;
    }

    .severity-info {
      border-left: 4px solid #17a2b8;
    }

    .badge {
      display: inline-block;
      padding: 3px 8px;
      border-radius: 3px;
      font-size: 12px;
      font-weight: 600;
      text-transform: uppercase;
      margin-right: 10px;
    }

    .badge-critical {
      background: #dc3545;
      color: white;
    }

    .badge-error {
      background: #fd7e14;
      color: white;
    }

    .badge-warning {
      background: #ffc107;
      color: #000;
    }

    .badge-info {
      background: #17a2b8;
      color: white;
    }

    .task-list {
      background: #f8f9fa;
      padding: 15px;
      border-radius: 5px;
      margin: 15px 0;
    }

    .task-list ul {
      margin-left: 20px;
    }

    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 2px solid #e0e0e0;
      text-align: center;
      color: #6c757d;
      font-size: 14px;
    }

    ul {
      margin: 10px 0;
      padding-left: 20px;
    }

    li {
      margin: 5px 0;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>Analysis Report: ${report.type.replace(/_/g, " ").toUpperCase()}</h1>

    <div class="metadata">
      <p><strong>Report ID:</strong> ${report.id}</p>
      <p><strong>Started:</strong> ${new Date(report.startedAt).toLocaleString()}</p>
      ${report.completedAt ? `<p><strong>Completed:</strong> ${new Date(report.completedAt).toLocaleString()}</p>` : ""}
      <p><strong>Projects Analyzed:</strong> ${report.projectIds.length}</p>
    </div>

    <h2>Summary</h2>
    <div class="summary">
      ${report.summary}
    </div>

    ${
      report.projectReports && report.projectReports.length > 0
        ? `
    <h2>Project Reports</h2>
    ${report.projectReports
      .map(
        (pr) => `
    <div class="project-report">
      <h3>${pr.projectName}</h3>
      <ul>
        <li><strong>Health Score:</strong> ${pr.healthScore}/100</li>
        <li><strong>Open Issues:</strong> ${pr.openIssues}</li>
        <li><strong>Open PRs:</strong> ${pr.openPRs}</li>
        <li><strong>CI Status:</strong> ${pr.ciStatus}</li>
      </ul>
      ${
        pr.risks.length > 0
          ? `
      <p><strong>Risks:</strong></p>
      <ul>
        ${pr.risks.map((risk) => `<li>${risk}</li>`).join("")}
      </ul>
      `
          : ""
      }
    </div>
    `
      )
      .join("")}
    `
        : ""
    }

    ${
      report.findings.length > 0
        ? `
    <h2>Findings</h2>
    ${["critical", "error", "warning", "info"]
      .map((severity) => {
        const findings = findingsBySeverity[severity as keyof typeof findingsBySeverity];
        if (!findings || findings.length === 0) return "";

        return `
    <h3>${severity.toUpperCase()} (${findings.length})</h3>
    ${findings
      .map(
        (finding) => `
    <div class="finding severity-${severity}">
      <h4>
        <span class="badge badge-${severity}">${severity}</span>
        ${finding.title}
      </h4>
      <p><strong>Category:</strong> ${finding.category}</p>
      <p><strong>Project:</strong> ${finding.projectId}</p>
      <p style="margin-top: 10px;">${finding.description}</p>
    </div>
    `
      )
      .join("")}
    `;
      })
      .join("")}
    `
        : ""
    }

    ${
      report.generatedTasks.length > 0
        ? `
    <h2>Generated Tasks</h2>
    <div class="task-list">
      <p>This analysis generated <strong>${report.generatedTasks.length}</strong> tasks.</p>
      <p><strong>Task IDs:</strong></p>
      <ul>
        ${report.generatedTasks.map((taskId) => `<li>${taskId}</li>`).join("")}
      </ul>
    </div>
    `
        : ""
    }

    <div class="footer">
      <p>Generated by Envisionbot on ${new Date().toLocaleString()}</p>
    </div>
  </div>
</body>
</html>
    `.trim();
  }

  /**
   * Group findings by severity
   */
  private static groupFindingsBySeverity(findings: Finding[]): Record<Finding["severity"], Finding[]> {
    return findings.reduce(
      (acc, finding) => {
        if (!acc[finding.severity]) {
          acc[finding.severity] = [];
        }
        acc[finding.severity].push(finding);
        return acc;
      },
      {} as Record<Finding["severity"], Finding[]>
    );
  }
}
